export const colorsLight = {
  BACKGROUND: '#F4F6F6',
  ON_BACKGROUND: '#191C1B',

  // Background primary color
  PRIMARY_COLOR: '#67b7ed',
  ON_PRIMARY: '#FFFFFF',
  SECONDARY_COLOR: '#4981dd',

  // Background
  BACKGROUND_SCREEN_COLOR: '#FFFFFF',

  // SURFACE
  SURFACE_1: '#FFFFFF',

  // CONTENT
  CONTENT_PRIMARY: '#191C1B',
  CONTENT_SECONDARY: '#3F4947',

  // Text color
  PRIMARY_TEXT_COLOR: '#263238',
  SECONDARY_TEXT_COLOR: '#757575',
  DISABLED_TEXT_COLOR: '#BABBBF',
  TEXT_SIMPLE_COLOR: 'rgba(44, 62, 80, 0.2)',

  // TextInput color
  BACKGROUND_TEXT_INPUT_COLOR: '#F8F8F8',

  // Button
  BACKGROUND_BUTTON_COLOR: '#FFFFFF',
  BUTTON_TEXT_CONTAINED_COLOR: '#FFFFFF',
  BUTTON_TEXT_OUTLINED_COLOR: '#67b7ed',
  BUTTON_TEXT_COLOR: '#000000',
  BUTTON_BORDER_COLOR: '#67b7ed',
  BUTTON_DISABLED_COLOR: '#CDD1D0',
  BUTTON_DISABLED_TEXT_COLOR: '#AAB0B6',

  // Bottom Tab
  BOTTOM_TAB_COLOR: '#000000',

  // GRAY
  GRAY_01: '#F8F8F8',
  GRAY_02: '#CDD1D0',
  GRAY_03: '#777B85',
  GRAY_04: '#999999',
  GRAY_05: '#F0F0F0',
  GRAY_06: '#999999',

  // Alert color
  SUCCESS_COLOR: '#36B37E',
  WARNING_COLOR: '#EAB55C',
  ERROR_COLOR: '#DC6358',
  INFO_COLOR: '#A3A1AF',

  WHATSAPP: '#25D366',
  FACEBOOK: '#3B5998',
  INSTAGRAM: '#C13584',
  TIKTOK: '#010101',

  // Basic color
  WHITE: '#FFFFFF',
  BLACK: '#000000',

  OUTLINE: '#BEC9C6',

  // SENTIMENT
  SENTIMENT_SUCCESS_BACKGROUND: '#F5FFF3',
  SENTIMENT_SUCCESS: '#006D3A',
  SENTIMENT_INFO_BACKGROUND: '#FFFFFF',
  SENTIMENT_INFO: '#00210D',
  SENTIMENT_WARNING_BACKGROUND: '#FFF8EF',
  SENTIMENT_WARNING: '#EDC843',
  SENTIMENT_NEGATIVE_ERROR_BACKGROUND: '#FFF8F7',
  SENTIMENT_NEGATIVE_COLOR: '#BA1A1A',
  SENTIMENT_TEXT: '#00210D',
  SENTIMENT_POSITIVE_BG: '#7FFBA8',
  SENTIMENT_WARNING_BACKGROUND_LOCK: '#FFE07E',
  SENTIMENT_WARNING_ON_WARNING_BG: '#231B00',

  // MAPS
  COLOR_MAP_LOSSES: '#FF6B6B',
  COLOR_MAP_FOUND: '#4ECDC4',
  COLOR_MAP_ADOPTION: '#FFD93D',
};
